/**
 * JSLab — Tutorials Data Part 2 (Lectures 25-45)
 * Author: Pranav Pushya
 */
LECTURES.push(
  {id:25,unit:2,title:"DOM — createElement, appendChild, removeChild",clo:"CLO07",difficulty:"Intermediate",readTime:"9 min",
    theory:"<h3>Creating Elements</h3><p><code>document.createElement(tag)</code> creates a new HTML element in memory. It is not visible until you add it to the DOM using methods like <code>appendChild</code> or <code>append</code>.</p><h3>Adding Elements</h3><ul><li><code>parent.appendChild(child)</code> — adds child as the last child of parent</li><li><code>parent.append(child)</code> — similar but can also append text</li><li><code>parent.prepend(child)</code> — adds as the first child</li><li><code>parent.insertBefore(new, ref)</code> — insert before a reference node</li></ul><h3>Removing Elements</h3><ul><li><code>parent.removeChild(child)</code> — removes a child node</li><li><code>element.remove()</code> — removes the element itself (modern)</li></ul><div class='analogy-box'><strong>Analogy:</strong> createElement is like building a LEGO piece. appendChild is snapping it onto the structure. removeChild is detaching it.</div>",
    examples:[{title:"Create and add elements",code:"// Create a new paragraph\nconst p = document.createElement('p');\np.textContent = 'Hello from JavaScript!';\np.classList.add('fade-in');\n\n// Add it to the page\ndocument.body.appendChild(p);\n\n// Create a list item and add to a list\nconst li = document.createElement('li');\nli.textContent = 'New item';\nconst list = document.querySelector('ul');\nif (list) list.appendChild(li);\n\nconsole.log('Elements created and added!');"},{title:"Remove elements",code:"// Remove using removeChild\nconst parent = document.querySelector('.container');\nconst child = document.querySelector('.old-item');\nif (parent && child) parent.removeChild(child);\n\n// Remove using element.remove() — modern way\nconst toast = document.querySelector('.notification');\nif (toast) toast.remove();\n\n// Replace content entirely\nconst box = document.getElementById('output');\nif (box) {\n  box.innerHTML = ''; // clear all children\n  const fresh = document.createElement('span');\n  fresh.textContent = 'Fresh content!';\n  box.appendChild(fresh);\n}"}],
    quickRef:[{syntax:"document.createElement('div')",desc:"Create a new element"},{syntax:"parent.appendChild(el)",desc:"Add element as last child"},{syntax:"el.remove()",desc:"Remove element from DOM"},{syntax:"parent.insertBefore(new, ref)",desc:"Insert before reference node"}],
    miniQuiz:[{q:"What does createElement do?",options:["Adds element to page","Creates element in memory (not visible yet)","Deletes an element","Copies an element"],correct:1,explanation:"createElement creates an element in memory. You must add it to the DOM with appendChild or similar to make it visible."},{q:"What is the modern way to remove an element?",options:["parent.removeChild(el)","el.remove()","el.delete()","document.remove(el)"],correct:1,explanation:"element.remove() is the modern, simpler way to remove an element from the DOM."},{q:"What does innerHTML = '' do?",options:["Deletes the element","Clears all child elements and content","Sets text to empty string","Has no effect"],correct:1,explanation:"Setting innerHTML to an empty string removes all child nodes and content from the element."}]
  },
  {id:26,unit:2,title:"DOM — Styling with CSS via JS",clo:"CLO07",difficulty:"Intermediate",readTime:"8 min",
    theory:"<h3>Inline Styles via style Property</h3><p>Every DOM element has a <code>style</code> property that lets you set inline CSS. Property names use camelCase: <code>backgroundColor</code> instead of <code>background-color</code>.</p><h3>classList API</h3><p>The preferred way to style elements dynamically is by adding/removing CSS classes using the <code>classList</code> API:</p><ul><li><code>classList.add('name')</code> — add a class</li><li><code>classList.remove('name')</code> — remove a class</li><li><code>classList.toggle('name')</code> — toggle on/off</li><li><code>classList.contains('name')</code> — check if class exists</li><li><code>classList.replace('old', 'new')</code> — replace a class</li></ul><h3>Reading Computed Styles</h3><p><code>getComputedStyle(element)</code> returns the final computed CSS values after all stylesheets and inline styles are applied.</p><div class='analogy-box'><strong>Best Practice:</strong> Prefer classList over inline styles. Keep styling in CSS files and use JS only to toggle classes. This keeps concerns separated.</div>",
    examples:[{title:"Inline styles and classList",code:"const card = document.createElement('div');\n\n// Inline styles\ncard.style.padding = '20px';\ncard.style.backgroundColor = 'rgba(255,255,255,0.05)';\ncard.style.borderRadius = '12px';\ncard.style.transition = 'all 0.3s ease';\n\n// classList (preferred)\ncard.classList.add('glass-card', 'fade-in');\nconsole.log(card.classList.contains('glass-card')); // true\n\ncard.classList.toggle('active'); // adds\ncard.classList.toggle('active'); // removes\n\ncard.classList.replace('fade-in', 'slide-in');\nconsole.log(card.className); // glass-card slide-in"},{title:"Reading computed styles",code:"const el = document.querySelector('.glass-card');\nif (el) {\n  const styles = getComputedStyle(el);\n  console.log('Background:', styles.backgroundColor);\n  console.log('Font size:', styles.fontSize);\n  console.log('Padding:', styles.padding);\n}"}],
    quickRef:[{syntax:"el.style.fontSize = '16px'",desc:"Set inline style (camelCase)"},{syntax:"el.classList.add('a','b')",desc:"Add one or more classes"},{syntax:"el.classList.toggle('x')",desc:"Toggle class on/off"},{syntax:"getComputedStyle(el)",desc:"Get final computed CSS values"}],
    miniQuiz:[{q:"Why is classList preferred over inline styles?",options:["It is faster","It keeps styling in CSS and logic in JS (separation of concerns)","It uses less memory","Inline styles don't work"],correct:1,explanation:"classList keeps styles in CSS files and uses JS only to toggle classes, maintaining separation of concerns."},{q:"What case format do style properties use in JS?",options:["kebab-case","camelCase","snake_case","PascalCase"],correct:1,explanation:"CSS properties in JavaScript use camelCase: background-color becomes backgroundColor."},{q:"What does classList.replace() do?",options:["Replaces element content","Swaps one class for another","Replaces all classes","Replaces the element"],correct:1,explanation:"classList.replace('oldClass', 'newClass') swaps the old class for the new one."}]
  },
  {id:27,unit:2,title:"Event Handling — addEventListener",clo:"CLO08",difficulty:"Intermediate",readTime:"10 min",
    theory:"<h3>What Are Events?</h3><p>Events are actions that happen in the browser: clicks, key presses, mouse movements, form submissions, page loads, etc. JavaScript can listen for these events and respond with code.</p><h3>addEventListener</h3><p><code>element.addEventListener(event, handler)</code> attaches an event listener. The first argument is the event name (string), the second is the callback function that runs when the event fires.</p><h3>Common Events</h3><ul><li><code>click</code> — element is clicked</li><li><code>mouseover</code> / <code>mouseout</code> — mouse enters/leaves</li><li><code>keydown</code> / <code>keyup</code> — keyboard key pressed/released</li><li><code>submit</code> — form submitted</li><li><code>input</code> — input value changes</li><li><code>load</code> — page/resource finished loading</li><li><code>DOMContentLoaded</code> — HTML parsed and ready</li></ul><h3>The Event Object</h3><p>The callback receives an event object with useful properties like <code>event.target</code> (the element that triggered it), <code>event.type</code>, and methods like <code>event.preventDefault()</code>.</p>",
    examples:[{title:"addEventListener basics",code:"const btn = document.createElement('button');\nbtn.textContent = 'Click Me';\nbtn.classList.add('btn', 'btn-primary');\n\nbtn.addEventListener('click', function(event) {\n  console.log('Button clicked!');\n  console.log('Target:', event.target.textContent);\n  console.log('Event type:', event.type);\n});\n\ndocument.body.appendChild(btn);\n\n// Keyboard event\ndocument.addEventListener('keydown', function(e) {\n  console.log('Key pressed:', e.key);\n  if (e.key === 'Escape') {\n    console.log('Escape pressed!');\n  }\n});"},{title:"Multiple events and removeEventListener",code:"function handleClick() {\n  console.log('Clicked!');\n}\n\nconst box = document.createElement('div');\nbox.textContent = 'Click me then I will stop listening';\n\n// Add listener\nbox.addEventListener('click', handleClick);\n\n// Remove after 5 seconds\nsetTimeout(function() {\n  box.removeEventListener('click', handleClick);\n  box.textContent = 'No longer listening!';\n  console.log('Listener removed');\n}, 5000);\n\ndocument.body.appendChild(box);"}],
    quickRef:[{syntax:"el.addEventListener('click', fn)",desc:"Listen for click events"},{syntax:"event.target",desc:"Element that triggered the event"},{syntax:"event.preventDefault()",desc:"Stop default browser behavior"},{syntax:"el.removeEventListener('click', fn)",desc:"Remove an event listener"}],
    miniQuiz:[{q:"What does addEventListener do?",options:["Creates an event","Attaches a function to run when an event occurs","Removes an event","Stops event propagation"],correct:1,explanation:"addEventListener attaches a callback function that runs whenever the specified event occurs on the element."},{q:"What is event.target?",options:["The parent element","The element that triggered the event","The event type","The callback function"],correct:1,explanation:"event.target refers to the actual DOM element that triggered the event."},{q:"How do you stop a form from submitting?",options:["return false","event.preventDefault()","event.stopPropagation()","form.stop()"],correct:1,explanation:"event.preventDefault() stops the default browser action, such as form submission or link navigation."}]
  },
  {id:28,unit:2,title:"Event Bubbling & Capturing",clo:"CLO08",difficulty:"Advanced",readTime:"10 min",
    theory:"<h3>Event Propagation</h3><p>When an event fires, it does not just trigger on the target element. It travels through the DOM in three phases:</p><ol><li><strong>Capturing phase:</strong> Event travels down from the document root to the target</li><li><strong>Target phase:</strong> Event reaches the target element</li><li><strong>Bubbling phase:</strong> Event bubbles back up from target to root</li></ol><h3>Event Bubbling</h3><p>By default, events bubble up. If you click a <code>&lt;button&gt;</code> inside a <code>&lt;div&gt;</code>, both the button's and div's click handlers fire. The button fires first (target), then the div (bubble).</p><h3>Event Capturing</h3><p>To listen during the capture phase, pass <code>true</code> as the third argument to addEventListener: <code>el.addEventListener('click', fn, true)</code>.</p><h3>Stopping Propagation</h3><p><code>event.stopPropagation()</code> stops the event from traveling further up (or down) the DOM tree.</p><div class='analogy-box'><strong>Analogy:</strong> Bubbling is like dropping a stone in water — ripples spread outward from the center. Capturing is the reverse — the wave comes inward from the edges toward the center.</div>",
    examples:[{title:"Bubbling demonstration",code:"// Create nested elements\nconst outer = document.createElement('div');\nouter.style.padding = '30px';\nouter.style.background = 'rgba(79,195,247,0.1)';\nouter.textContent = 'Outer div';\n\nconst inner = document.createElement('button');\ninner.textContent = 'Inner button';\ninner.classList.add('btn', 'btn-primary');\nouter.appendChild(inner);\n\n// Both will fire on button click (bubbling)\nouter.addEventListener('click', () => console.log('Outer clicked'));\ninner.addEventListener('click', () => console.log('Inner clicked'));\n// Click button → 'Inner clicked' then 'Outer clicked'\n\ndocument.body.appendChild(outer);"},{title:"Stop propagation",code:"const parent = document.createElement('div');\nparent.textContent = 'Parent';\nconst child = document.createElement('button');\nchild.textContent = 'Child — click me';\nchild.classList.add('btn','btn-secondary');\nparent.appendChild(child);\n\nparent.addEventListener('click', () => console.log('Parent!'));\nchild.addEventListener('click', (e) => {\n  e.stopPropagation(); // stops bubbling\n  console.log('Child only!');\n});\n// Click child → only 'Child only!' (parent not triggered)\n\ndocument.body.appendChild(parent);"}],
    quickRef:[{syntax:"Bubbling",desc:"Event goes from target up to root (default)"},{syntax:"Capturing",desc:"Event goes from root down to target"},{syntax:"e.stopPropagation()",desc:"Stop event from traveling further"},{syntax:"addEventListener(e, fn, true)",desc:"Listen in capture phase"}],
    miniQuiz:[{q:"In what order do bubbling events fire?",options:["Root to target","Target to root","Random order","Only on target"],correct:1,explanation:"In bubbling, events fire on the target first, then propagate upward through each ancestor to the root."},{q:"How do you listen during the capture phase?",options:["Use captureEvent()","Pass true as third arg to addEventListener","Use event.capture","It is automatic"],correct:1,explanation:"Pass true as the third argument: element.addEventListener('click', handler, true) to listen during capture."},{q:"What does stopPropagation() do?",options:["Stops the callback","Prevents default action","Stops event from propagating to other elements","Removes the listener"],correct:2,explanation:"stopPropagation() stops the event from traveling further — it won't reach parent elements (bubbling) or child elements (capturing)."}]
  },
  {id:29,unit:2,title:"Event Delegation & Form Validation",clo:"CLO08",difficulty:"Advanced",readTime:"11 min",
    theory:"<h3>Event Delegation</h3><p>Instead of attaching a listener to every child element, attach one listener to the parent. Use <code>event.target</code> to determine which child was clicked. This is efficient and works for dynamically added elements.</p><h3>Why Use Delegation?</h3><ul><li>Fewer event listeners = better performance</li><li>Works with elements added after the listener was set up</li><li>Cleaner code — one handler instead of many</li></ul><h3>Form Validation with JS</h3><p>Use the <code>submit</code> event on forms. Call <code>event.preventDefault()</code> to stop submission, then validate fields. Display error messages by manipulating the DOM.</p><div class='analogy-box'><strong>Analogy:</strong> Event delegation is like a receptionist in an office. Instead of each employee answering the door, the receptionist handles visitors and directs them to the right person.</div>",
    examples:[{title:"Event delegation",code:"// One listener on parent handles all children\nconst list = document.createElement('ul');\nlist.innerHTML = '<li>Item 1</li><li>Item 2</li><li>Item 3</li>';\n\nlist.addEventListener('click', function(e) {\n  if (e.target.tagName === 'LI') {\n    console.log('Clicked:', e.target.textContent);\n    e.target.style.color = '#69f0ae';\n  }\n});\n\n// Works for new items too!\nconst newItem = document.createElement('li');\nnewItem.textContent = 'Item 4 (added later)';\nlist.appendChild(newItem);\n\ndocument.body.appendChild(list);"},{title:"Form validation",code:"function validateForm() {\n  const email = 'test@example.com';\n  const password = '12345';\n  const errors = [];\n\n  if (!email.includes('@')) {\n    errors.push('Invalid email address');\n  }\n  if (password.length < 8) {\n    errors.push('Password must be at least 8 characters');\n  }\n\n  if (errors.length > 0) {\n    console.log('Validation failed:');\n    errors.forEach(e => console.log('❌ ' + e));\n    return false;\n  }\n  console.log('✅ Form is valid!');\n  return true;\n}\nvalidateForm();"}],
    quickRef:[{syntax:"parent.addEventListener('click', fn)",desc:"Delegate events to parent"},{syntax:"event.target.tagName",desc:"Check which element was actually clicked"},{syntax:"event.preventDefault()",desc:"Prevent form submission"},{syntax:"form.checkValidity()",desc:"Native HTML5 validation check"}],
    miniQuiz:[{q:"What is event delegation?",options:["Attaching listeners to every element","Attaching one listener to a parent to handle child events","Delegating code to another file","Removing events from children"],correct:1,explanation:"Event delegation means putting one listener on a parent element and using event.target to handle clicks on child elements."},{q:"Why does delegation work for dynamically added elements?",options:["It uses a special API","The listener is on the parent, not the child","It refreshes automatically","It uses MutationObserver"],correct:1,explanation:"Since the listener is on the parent (which already exists), any child added later will also trigger the parent's listener when clicked."},{q:"How do you prevent a form from submitting?",options:["return false","form.stop()","event.preventDefault()","event.stopSubmission()"],correct:2,explanation:"Call event.preventDefault() inside the submit event handler to stop the form from submitting and navigate."}]
  },
  {id:30,unit:2,title:"DOM Performance Optimizations",clo:"CLO08",difficulty:"Advanced",readTime:"8 min",
    theory:"<h3>Avoiding Reflows and Repaints</h3><p>Every time you change the DOM, the browser may need to recalculate layout (reflow) and redraw (repaint). Multiple changes trigger multiple reflows, which slows down your page.</p><h3>Batch Updates with DocumentFragment</h3><p>Use <code>document.createDocumentFragment()</code> to build DOM changes off-screen, then add the fragment to the page in one operation.</p><h3>Use textContent over innerHTML</h3><p>Setting <code>innerHTML</code> forces the browser to parse HTML. <code>textContent</code> is faster for plain text.</p><h3>Performance Tips</h3><ul><li>Cache DOM queries — don't call querySelector repeatedly for the same element</li><li>Use CSS classes instead of multiple style changes</li><li>Avoid layout thrashing — don't read then write repeatedly</li><li>Use requestAnimationFrame for visual changes</li></ul>",
    examples:[{title:"DocumentFragment for batch updates",code:"const fragment = document.createDocumentFragment();\n\nfor (let i = 0; i < 100; i++) {\n  const li = document.createElement('li');\n  li.textContent = 'Item ' + (i + 1);\n  fragment.appendChild(li); // adds to fragment, not DOM\n}\n\n// One single DOM update\nconst list = document.createElement('ul');\nlist.appendChild(fragment);\nconsole.log('100 items added in one operation');\nconsole.log('List has', list.children.length, 'children');"},{title:"Cache DOM references",code:"// BAD — queries DOM every iteration\nfor (let i = 0; i < 10; i++) {\n  // document.querySelector('.output') runs 10 times!\n}\n\n// GOOD — cache the reference\nconst output = document.querySelector('.output') || document.body;\nfor (let i = 0; i < 10; i++) {\n  // Use cached 'output' variable\n}\nconsole.log('DOM reference cached — much faster!');"}],
    quickRef:[{syntax:"document.createDocumentFragment()",desc:"Create off-screen container for batch DOM updates"},{syntax:"requestAnimationFrame(fn)",desc:"Schedule visual updates for next frame"},{syntax:"Cache DOM queries",desc:"Store querySelector results in variables"}],
    miniQuiz:[{q:"What is a reflow?",options:["A JavaScript error","Browser recalculating element positions and sizes","A CSS animation","A page refresh"],correct:1,explanation:"A reflow is when the browser recalculates the layout — positions and sizes of elements. It is expensive."},{q:"Why use DocumentFragment?",options:["It is required by the spec","It batches DOM changes into one update","It makes elements invisible","It caches CSS"],correct:1,explanation:"DocumentFragment lets you build DOM changes in memory and add them all at once, triggering only one reflow."},{q:"What is layout thrashing?",options:["Deleting many elements","Rapidly reading and writing DOM properties causing repeated reflows","Using too many event listeners","Having too much CSS"],correct:1,explanation:"Layout thrashing happens when you alternate between reading and writing DOM properties, forcing the browser to recalculate layout repeatedly."}]
  }
);
