/**
 * JSLab — Tutorials Data Part 3 (Lectures 31-45)
 * Author: Pranav Pushya
 */
LECTURES.push(
  {id:31,unit:2,title:"BOM — window Object",clo:"CLO09",difficulty:"Intermediate",readTime:"8 min",
    theory:"<h3>What Is the BOM?</h3><p>The Browser Object Model (BOM) allows JavaScript to interact with the browser itself, not just the page content. The <code>window</code> object is the top-level object — it represents the browser window.</p><h3>window Properties</h3><ul><li><code>window.innerWidth</code> / <code>window.innerHeight</code> — viewport size</li><li><code>window.scrollX</code> / <code>window.scrollY</code> — scroll position</li><li><code>window.location</code> — current URL info</li><li><code>window.navigator</code> — browser info</li><li><code>window.history</code> — browsing history</li></ul><p>Note: The <code>window</code> prefix is optional. You can write <code>innerWidth</code> instead of <code>window.innerWidth</code>.</p>",
    examples:[{title:"Window properties",code:"console.log('Viewport width:', window.innerWidth);\nconsole.log('Viewport height:', window.innerHeight);\nconsole.log('Scroll X:', window.scrollX);\nconsole.log('Scroll Y:', window.scrollY);\nconsole.log('Current URL:', window.location.href);\nconsole.log('Browser:', window.navigator.userAgent);"},{title:"Window methods",code:"// Scroll to top\n// window.scrollTo({ top: 0, behavior: 'smooth' });\n\n// Open new window\n// window.open('https://google.com', '_blank');\n\nconsole.log('Screen width:', screen.width);\nconsole.log('Screen height:', screen.height);\nconsole.log('Online status:', navigator.onLine);"}],
    quickRef:[{syntax:"window.innerWidth",desc:"Browser viewport width"},{syntax:"window.location.href",desc:"Current page URL"},{syntax:"window.navigator",desc:"Browser information object"},{syntax:"window.scrollTo()",desc:"Scroll to specific position"}],
    miniQuiz:[{q:"What does the BOM allow?",options:["Database access","Interaction with the browser window","CSS styling","Server-side code"],correct:1,explanation:"The BOM lets JavaScript interact with the browser — window size, URL, history, etc."},{q:"Is the window prefix required?",options:["Yes always","No, it is optional for global properties","Only in strict mode","Only for methods"],correct:1,explanation:"The window prefix is optional. innerWidth and window.innerWidth are equivalent."},{q:"What does window.innerWidth return?",options:["Screen resolution","Viewport width in pixels","Document width","Window border width"],correct:1,explanation:"window.innerWidth returns the width of the browser viewport (visible area) in pixels."}]
  },
  {id:32,unit:2,title:"BOM — navigator & location",clo:"CLO09",difficulty:"Intermediate",readTime:"7 min",
    theory:"<h3>navigator Object</h3><p>The <code>navigator</code> object provides info about the browser:</p><ul><li><code>navigator.userAgent</code> — browser identification string</li><li><code>navigator.language</code> — browser language</li><li><code>navigator.onLine</code> — online/offline status</li><li><code>navigator.platform</code> — operating system</li></ul><h3>location Object</h3><p>The <code>location</code> object provides URL information and navigation:</p><ul><li><code>location.href</code> — full URL</li><li><code>location.hostname</code> — domain name</li><li><code>location.pathname</code> — path after domain</li><li><code>location.search</code> — query string (?key=value)</li><li><code>location.hash</code> — fragment (#section)</li><li><code>location.reload()</code> — refresh the page</li><li><code>location.assign(url)</code> — navigate to new URL</li></ul>",
    examples:[{title:"Navigator and location",code:"// Navigator info\nconsole.log('User Agent:', navigator.userAgent);\nconsole.log('Language:', navigator.language);\nconsole.log('Online:', navigator.onLine);\nconsole.log('Platform:', navigator.platform);\n\n// Location info\nconsole.log('Full URL:', location.href);\nconsole.log('Hostname:', location.hostname);\nconsole.log('Path:', location.pathname);\nconsole.log('Protocol:', location.protocol);"},{title:"URL manipulation",code:"// Parse URL parts\nconst url = new URL('https://example.com/path?name=Pranav&course=FE1#section');\nconsole.log('Host:', url.hostname);   // example.com\nconsole.log('Path:', url.pathname);   // /path\nconsole.log('Search:', url.search);   // ?name=Pranav&course=FE1\nconsole.log('Hash:', url.hash);       // #section\n\n// Get query parameters\nconst params = url.searchParams;\nconsole.log('Name:', params.get('name'));     // Pranav\nconsole.log('Course:', params.get('course')); // FE1"}],
    quickRef:[{syntax:"navigator.onLine",desc:"Check if browser is online"},{syntax:"location.href",desc:"Get or set the current URL"},{syntax:"location.reload()",desc:"Refresh the page"},{syntax:"location.assign(url)",desc:"Navigate to a new URL"}],
    miniQuiz:[{q:"What does navigator.onLine return?",options:["The URL","A boolean (true if online)","The network speed","The IP address"],correct:1,explanation:"navigator.onLine returns true if the browser is connected to the internet, false otherwise."},{q:"How do you navigate to a new URL?",options:["navigator.goto(url)","location.assign(url)","document.navigate(url)","window.go(url)"],correct:1,explanation:"location.assign(url) navigates the browser to the specified URL."},{q:"What does location.search contain?",options:["The search bar text","Query string parameters (?key=value)","Search engine results","The page title"],correct:1,explanation:"location.search contains the query string of the URL, including the ? character."}]
  },
  {id:33,unit:2,title:"Dialogs — alert, confirm, prompt",clo:"CLO09",difficulty:"Beginner",readTime:"6 min",
    theory:"<h3>Browser Dialog Methods</h3><p>JavaScript provides three built-in dialog methods:</p><ul><li><code>alert(message)</code> — shows an info box with OK button. Blocks execution until dismissed.</li><li><code>confirm(message)</code> — shows a box with OK and Cancel. Returns <code>true</code> (OK) or <code>false</code> (Cancel).</li><li><code>prompt(message, default)</code> — shows an input box. Returns the entered text, or <code>null</code> if canceled.</li></ul><div class='analogy-box'><strong>Note:</strong> These dialogs block the main thread and are considered bad UX in modern web apps. Use custom modal dialogs instead. They are still useful for quick testing and learning.</div>",
    examples:[{title:"alert, confirm, prompt",code:"// alert — information\n// alert('Hello, Pranav!');\nconsole.log('alert() shows an info popup');\n\n// confirm — yes/no decision\nconst willProceed = true; // confirm('Are you sure?');\nconsole.log('User confirmed:', willProceed);\n\n// prompt — get user input\nconst name = 'Pranav'; // prompt('Enter your name:', 'Student');\nconsole.log('User entered:', name);\n\nif (willProceed) {\n  console.log('User chose to proceed');\n} else {\n  console.log('User cancelled');\n}"}],
    quickRef:[{syntax:"alert('msg')",desc:"Show info popup with OK"},{syntax:"confirm('msg')",desc:"Show OK/Cancel, returns boolean"},{syntax:"prompt('msg', 'default')",desc:"Show text input, returns string or null"}],
    miniQuiz:[{q:"What does confirm() return?",options:["A string","true or false","undefined","The message text"],correct:1,explanation:"confirm() returns true if the user clicks OK, or false if they click Cancel."},{q:"What does prompt() return if user clicks Cancel?",options:["Empty string","false","null","undefined"],correct:2,explanation:"If the user clicks Cancel on a prompt dialog, it returns null."},{q:"Why are these dialogs considered bad practice in modern apps?",options:["They are slow","They block the main thread and break the user experience","They don't work on mobile","They are deprecated"],correct:1,explanation:"Alert, confirm, and prompt are blocking — they freeze all JavaScript execution until dismissed, creating a poor user experience."}]
  },
  {id:34,unit:2,title:"Timers — setTimeout, setInterval",clo:"CLO09",difficulty:"Intermediate",readTime:"9 min",
    theory:"<h3>setTimeout</h3><p><code>setTimeout(callback, delay)</code> executes a function once after a specified delay in milliseconds. It returns a timer ID that can be used with <code>clearTimeout()</code> to cancel it.</p><h3>setInterval</h3><p><code>setInterval(callback, interval)</code> executes a function repeatedly at the specified interval. Use <code>clearInterval()</code> to stop it.</p><h3>Important Notes</h3><ul><li>Delays are in milliseconds (1000ms = 1 second)</li><li>Timers are asynchronous — code after them runs immediately</li><li>Always clear intervals when done to avoid memory leaks</li><li>Minimum delay is ~4ms due to browser throttling</li></ul>",
    examples:[{title:"setTimeout and setInterval",code:"// setTimeout — runs once after delay\nconsole.log('Start');\nsetTimeout(function() {\n  console.log('This runs after 1 second');\n}, 1000);\nconsole.log('This runs immediately (async!)');\n\n// setInterval — runs repeatedly\nlet count = 0;\nconst timer = setInterval(function() {\n  count++;\n  console.log('Tick:', count);\n  if (count >= 5) {\n    clearInterval(timer);\n    console.log('Timer stopped!');\n  }\n}, 500);"},{title:"Countdown timer",code:"function startCountdown(seconds) {\n  let remaining = seconds;\n  console.log('Countdown:', remaining);\n  \n  const interval = setInterval(function() {\n    remaining--;\n    console.log('Countdown:', remaining);\n    if (remaining <= 0) {\n      clearInterval(interval);\n      console.log('Time is up!');\n    }\n  }, 1000);\n  \n  return interval;\n}\n\nconst myTimer = startCountdown(5);"}],
    quickRef:[{syntax:"setTimeout(fn, ms)",desc:"Run function once after delay"},{syntax:"setInterval(fn, ms)",desc:"Run function repeatedly at interval"},{syntax:"clearTimeout(id)",desc:"Cancel a setTimeout"},{syntax:"clearInterval(id)",desc:"Stop a setInterval"}],
    miniQuiz:[{q:"What does setTimeout do?",options:["Pauses JavaScript","Runs a function once after a delay","Runs a function repeatedly","Slows down code"],correct:1,explanation:"setTimeout schedules a function to run once after the specified delay. It does not pause other code."},{q:"How do you stop a setInterval?",options:["interval.stop()","clearInterval(id)","stopInterval(id)","setInterval(null)"],correct:1,explanation:"clearInterval(id) stops a running interval timer. Pass it the ID returned by setInterval."},{q:"Are timers synchronous or asynchronous?",options:["Synchronous","Asynchronous","Both","Neither"],correct:1,explanation:"Timers are asynchronous — code after setTimeout/setInterval runs immediately without waiting for the timer."}]
  },
  {id:35,unit:3,title:"Callback Functions & Callback Hell",clo:"CLO10",difficulty:"Intermediate",readTime:"10 min",
    theory:"<h3>What Is a Callback?</h3><p>A callback is a function passed as an argument to another function. The receiving function calls it later, usually when an operation is complete. Callbacks are the foundation of asynchronous JavaScript.</p><h3>Synchronous Callbacks</h3><p>Some callbacks run immediately, like those in <code>forEach</code>, <code>map</code>, and <code>filter</code>.</p><h3>Asynchronous Callbacks</h3><p>Others run later, like in <code>setTimeout</code>, event listeners, and file/network operations.</p><h3>Callback Hell</h3><p>When you nest many asynchronous callbacks inside each other, the code becomes deeply indented and hard to read. This is called \"callback hell\" or \"pyramid of doom.\" Promises and async/await solve this problem.</p><div class='analogy-box'><strong>Analogy:</strong> A callback is like leaving your number at a restaurant — \"Call me when my table is ready.\" Callback hell is like leaving your number, then inside that call asking for another callback, and another, creating a chain of confusing phone calls.</div>",
    examples:[{title:"Callbacks — sync and async",code:"// Synchronous callback (runs immediately)\nconst nums = [1, 2, 3];\nnums.forEach(function(n) {\n  console.log('Sync callback:', n);\n});\n\n// Asynchronous callback (runs later)\nsetTimeout(function() {\n  console.log('Async callback: runs after 1s');\n}, 1000);\nconsole.log('This runs before the timeout!');"},{title:"Callback hell example",code:"// Callback hell — nested callbacks\nfunction step1(cb) { setTimeout(() => { console.log('Step 1 done'); cb(); }, 500); }\nfunction step2(cb) { setTimeout(() => { console.log('Step 2 done'); cb(); }, 500); }\nfunction step3(cb) { setTimeout(() => { console.log('Step 3 done'); cb(); }, 500); }\n\n// The 'pyramid of doom'\nstep1(function() {\n  step2(function() {\n    step3(function() {\n      console.log('All steps complete!');\n    });\n  });\n});\n// This nesting gets worse with more steps!"}],
    quickRef:[{syntax:"function doTask(callback) { callback(); }",desc:"Function that accepts a callback"},{syntax:"Callback hell",desc:"Deeply nested callbacks — hard to read"},{syntax:"Pyramid of doom",desc:"Another name for callback hell"}],
    miniQuiz:[{q:"What is a callback function?",options:["A function that returns another function","A function passed as argument to another function","A recursive function","An arrow function"],correct:1,explanation:"A callback is a function passed as an argument. The receiving function calls it back at the appropriate time."},{q:"What causes callback hell?",options:["Too many functions","Deeply nested asynchronous callbacks","Using arrow functions","Having too many parameters"],correct:1,explanation:"Callback hell occurs when many async callbacks are nested inside each other, creating deeply indented, hard-to-read code."},{q:"How is callback hell solved?",options:["More callbacks","Promises and async/await","Using var instead of let","Using switch statements"],correct:1,explanation:"Promises provide .then() chaining and async/await provides clean, flat syntax for handling async operations."}]
  },
  {id:36,unit:3,title:"Promises — States & Creation",clo:"CLO10",difficulty:"Intermediate",readTime:"11 min",
    theory:"<h3>What Is a Promise?</h3><p>A Promise is an object that represents the eventual completion (or failure) of an asynchronous operation. It is a cleaner alternative to callbacks for handling async code.</p><h3>Promise States</h3><ul><li><strong>Pending:</strong> Initial state — the operation has not completed yet</li><li><strong>Fulfilled:</strong> The operation completed successfully — <code>resolve(value)</code> was called</li><li><strong>Rejected:</strong> The operation failed — <code>reject(error)</code> was called</li></ul><p>A promise can only transition from pending to fulfilled or pending to rejected. Once settled, it cannot change.</p><h3>Creating a Promise</h3><p>Use <code>new Promise((resolve, reject) => { ... })</code>. Call <code>resolve(value)</code> on success and <code>reject(error)</code> on failure.</p><div class='analogy-box'><strong>Analogy:</strong> A Promise is like ordering food online. When you order (create promise), it is pending. When the food arrives, the promise is fulfilled. If the order is cancelled, it is rejected.</div>",
    examples:[{title:"Creating and using Promises",code:"// Creating a promise\nconst myPromise = new Promise((resolve, reject) => {\n  const success = true;\n  setTimeout(() => {\n    if (success) {\n      resolve('Data loaded!');\n    } else {\n      reject('Failed to load');\n    }\n  }, 1000);\n});\n\n// Consuming the promise\nmyPromise\n  .then(result => console.log('Success:', result))\n  .catch(error => console.log('Error:', error));\n\nconsole.log('Promise is pending...');"},{title:"Promise that simulates API call",code:"function fetchUser(id) {\n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      if (id > 0) {\n        resolve({ id: id, name: 'Pranav', course: 'FE-1' });\n      } else {\n        reject('Invalid user ID');\n      }\n    }, 800);\n  });\n}\n\nfetchUser(1)\n  .then(user => console.log('User:', user.name))\n  .catch(err => console.log('Error:', err));"}],
    quickRef:[{syntax:"new Promise((resolve, reject) => {})",desc:"Create a new Promise"},{syntax:".then(fn)",desc:"Handle successful result"},{syntax:".catch(fn)",desc:"Handle error/rejection"},{syntax:"Pending → Fulfilled or Rejected",desc:"Promise state transitions"}],
    miniQuiz:[{q:"What are the three states of a Promise?",options:["start, middle, end","loading, success, error","pending, fulfilled, rejected","open, closed, settled"],correct:2,explanation:"A Promise has three states: pending (initial), fulfilled (success via resolve), and rejected (failure via reject)."},{q:"Can a fulfilled promise become rejected?",options:["Yes","No — once settled, it cannot change","Only with .catch()","Only if you call reject again"],correct:1,explanation:"Once a Promise settles (fulfilled or rejected), its state is final and cannot change."},{q:"What does .catch() handle?",options:["Successful results","Rejected promises and errors","All promise states","Only network errors"],correct:1,explanation:".catch() handles rejected promises — it receives the error/reason passed to reject()."}]
  },
  {id:37,unit:3,title:"Promise Chaining — .then() & .catch()",clo:"CLO10",difficulty:"Intermediate",readTime:"9 min",
    theory:"<h3>Chaining .then()</h3><p>Each <code>.then()</code> returns a new Promise, allowing you to chain multiple async steps in sequence. The value returned from one <code>.then()</code> is passed as input to the next.</p><h3>Error Handling with .catch()</h3><p>A single <code>.catch()</code> at the end of the chain handles errors from any step. If any <code>.then()</code> throws or returns a rejected promise, the chain skips to <code>.catch()</code>.</p><h3>.finally()</h3><p><code>.finally()</code> runs regardless of success or failure — useful for cleanup operations like hiding loading spinners.</p>",
    examples:[{title:"Promise chaining",code:"function wait(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}\n\nwait(500)\n  .then(() => { console.log('Step 1'); return wait(500); })\n  .then(() => { console.log('Step 2'); return wait(500); })\n  .then(() => { console.log('Step 3'); return 'Done!'; })\n  .then(result => console.log(result))\n  .catch(err => console.log('Error:', err))\n  .finally(() => console.log('Cleanup complete'));"},{title:"Error propagation",code:"function riskyTask(n) {\n  return new Promise((resolve, reject) => {\n    setTimeout(() => {\n      if (n > 0) resolve(n * 2);\n      else reject('Number must be positive');\n    }, 300);\n  });\n}\n\nriskyTask(5)\n  .then(result => { console.log('Result:', result); return riskyTask(-1); })\n  .then(result => console.log('This never runs'))\n  .catch(err => console.log('Caught:', err));"}],
    quickRef:[{syntax:".then(fn).then(fn)",desc:"Chain sequential async operations"},{syntax:".catch(fn)",desc:"Handle any error in the chain"},{syntax:".finally(fn)",desc:"Runs after success or failure"}],
    miniQuiz:[{q:"What does .then() return?",options:["The original promise","A new promise","undefined","The callback result"],correct:1,explanation:".then() always returns a new Promise, which allows chaining."},{q:"Where should .catch() go in a chain?",options:["At the beginning","After every .then()","At the end to catch any error in the chain","It doesn't matter"],correct:2,explanation:"A single .catch() at the end of a chain handles errors from any preceding .then()."},{q:"What does .finally() do?",options:["Ends the promise","Runs cleanup code regardless of outcome","Catches errors","Creates a new promise"],correct:1,explanation:".finally() runs a callback after the promise settles, whether it was fulfilled or rejected. It's used for cleanup."}]
  },
  {id:38,unit:3,title:"async/await",clo:"CLO10",difficulty:"Intermediate",readTime:"10 min",
    theory:"<h3>What Is async/await?</h3><p><code>async/await</code> (ES2017) is syntactic sugar over Promises. It makes asynchronous code look and behave like synchronous code, making it much easier to read.</p><h3>async Functions</h3><p>Adding <code>async</code> before a function declaration makes it always return a Promise. Inside an async function, you can use <code>await</code> to pause execution until a Promise resolves.</p><h3>await Keyword</h3><p><code>await</code> pauses the async function until the Promise settles. If the Promise fulfills, await returns the value. If it rejects, it throws an error (catch with try/catch).</p><div class='analogy-box'><strong>Analogy:</strong> Promises with .then() are like passing notes — \"when you're done, tell the next person.\" async/await is like having a conversation — \"wait for the answer, then continue talking.\"</div>",
    examples:[{title:"async/await basics",code:"function delay(ms) {\n  return new Promise(resolve => setTimeout(resolve, ms));\n}\n\nasync function runSteps() {\n  console.log('Starting...');\n  await delay(500);\n  console.log('Step 1 done');\n  await delay(500);\n  console.log('Step 2 done');\n  await delay(500);\n  console.log('All done!');\n  return 'Complete';\n}\n\nrunSteps().then(r => console.log(r));"},{title:"Error handling with try/catch",code:"async function fetchData(shouldFail) {\n  try {\n    console.log('Fetching...');\n    await new Promise((resolve, reject) => {\n      setTimeout(() => {\n        if (shouldFail) reject('Network error');\n        else resolve();\n      }, 500);\n    });\n    console.log('Data received!');\n  } catch (error) {\n    console.log('Error caught:', error);\n  } finally {\n    console.log('Done (runs either way)');\n  }\n}\nfetchData(false);\nfetchData(true);"}],
    quickRef:[{syntax:"async function f() {}",desc:"Declare an async function (always returns Promise)"},{syntax:"const result = await promise",desc:"Wait for promise to resolve"},{syntax:"try { await ... } catch(e) {}",desc:"Handle async errors"}],
    miniQuiz:[{q:"What does the async keyword do?",options:["Makes code run faster","Makes the function return a Promise","Creates a new thread","Pauses all code"],correct:1,explanation:"The async keyword makes a function always return a Promise. It also enables the use of await inside it."},{q:"What does await do?",options:["Stops all JavaScript","Pauses only the async function until the Promise resolves","Creates a new Promise","Catches errors"],correct:1,explanation:"await pauses execution of the async function (not the whole program) until the awaited Promise settles."},{q:"How do you handle errors with async/await?",options:["Using .catch()",".then(null, fn)","try/catch blocks","All of the above work"],correct:3,explanation:"All three approaches work. try/catch is the most common with async/await, but .catch() on the returned promise also works."}]
  },
  {id:39,unit:3,title:"Error Handling — try/catch",clo:"CLO10",difficulty:"Intermediate",readTime:"8 min",
    theory:"<h3>Runtime Errors</h3><p>Errors can occur at any time: accessing undefined properties, network failures, JSON parsing, etc. Without error handling, a single error stops your entire script.</p><h3>try/catch/finally</h3><p>Wrap risky code in a <code>try</code> block. If an error occurs, the <code>catch</code> block runs with the error object. The <code>finally</code> block always runs, regardless of error.</p><h3>Throwing Errors</h3><p>Use <code>throw new Error('message')</code> to create custom errors. You can throw from anywhere — even inside functions — and catch them higher up.</p><h3>Error Object</h3><p>The error object has properties: <code>message</code> (description), <code>name</code> (type like TypeError, ReferenceError), and <code>stack</code> (call stack trace).</p>",
    examples:[{title:"try/catch/finally",code:"try {\n  const data = JSON.parse('{invalid json}');\n} catch (error) {\n  console.log('Error name:', error.name);     // SyntaxError\n  console.log('Error message:', error.message);\n} finally {\n  console.log('This always runs');\n}\n\n// Custom error\nfunction divide(a, b) {\n  if (b === 0) throw new Error('Cannot divide by zero');\n  return a / b;\n}\ntry {\n  console.log(divide(10, 2));  // 5\n  console.log(divide(10, 0));  // throws!\n} catch (e) {\n  console.log('Caught:', e.message);\n}"}],
    quickRef:[{syntax:"try { } catch(e) { }",desc:"Catch runtime errors"},{syntax:"throw new Error('msg')",desc:"Throw a custom error"},{syntax:"finally { }",desc:"Always runs after try/catch"},{syntax:"e.message, e.name, e.stack",desc:"Error object properties"}],
    miniQuiz:[{q:"What does the finally block do?",options:["Runs only on error","Runs only on success","Always runs regardless of error","Ends the program"],correct:2,explanation:"The finally block always runs — whether an error occurred or not. It's used for cleanup."},{q:"What does throw do?",options:["Deletes a variable","Creates and signals an error","Logs a message","Returns from a function"],correct:1,explanation:"throw creates an error and immediately jumps to the nearest catch block."},{q:"What is the name property of a TypeError?",options:["'Error'","'TypeError'","'type'","'runtime'"],correct:1,explanation:"The name property of a TypeError is the string 'TypeError'. Each error type has its matching name."}]
  },
  {id:40,unit:3,title:"Event Loop — Call Stack, Task Queue, Microtasks",clo:"CLO10",difficulty:"Advanced",readTime:"12 min",
    theory:"<h3>How JavaScript Runs Code</h3><p>JavaScript is single-threaded — it can only do one thing at a time. The event loop is the mechanism that enables async operations despite this limitation.</p><h3>The Call Stack</h3><p>The call stack is where functions execute. When a function is called, it is pushed onto the stack. When it returns, it is popped off. JavaScript processes one function at a time from the stack.</p><h3>Web APIs & Task Queue</h3><p>When you use setTimeout, addEventListener, or fetch, the browser handles these outside the call stack. When complete, the callback is placed in the task queue (also called macrotask queue).</p><h3>Microtask Queue</h3><p>Promises use a separate microtask queue that has higher priority. Microtasks run before the next macrotask. <code>.then()</code>, <code>.catch()</code>, and <code>await</code> use microtasks.</p><h3>The Event Loop</h3><p>The event loop checks: if the call stack is empty, take the next microtask. If no microtasks, take the next macrotask. Repeat forever.</p><div class='analogy-box'><strong>Analogy:</strong> The call stack is a chef cooking one dish at a time. Web APIs are kitchen assistants preparing ingredients. The task queue is a list of dishes waiting. Microtasks are VIP rush orders that jump ahead.</div>",
    examples:[{title:"Event loop order prediction",code:"console.log('1: Start');\n\nsetTimeout(() => {\n  console.log('2: setTimeout (macrotask)');\n}, 0);\n\nPromise.resolve().then(() => {\n  console.log('3: Promise (microtask)');\n});\n\nconsole.log('4: End');\n\n// Output order:\n// 1: Start\n// 4: End\n// 3: Promise (microtask — runs before macrotask)\n// 2: setTimeout (macrotask)"},{title:"Complex event loop",code:"console.log('A');\n\nsetTimeout(() => console.log('B'), 0);\n\nPromise.resolve()\n  .then(() => {\n    console.log('C');\n    return Promise.resolve();\n  })\n  .then(() => console.log('D'));\n\nconsole.log('E');\n\n// Output: A, E, C, D, B\n// A,E = sync; C,D = microtasks; B = macrotask"}],
    quickRef:[{syntax:"Call stack",desc:"Where currently executing functions live"},{syntax:"Task queue (macrotask)",desc:"setTimeout, setInterval callbacks"},{syntax:"Microtask queue",desc:"Promise .then/.catch, MutationObserver"},{syntax:"Event loop",desc:"Moves tasks from queues to call stack when empty"}],
    miniQuiz:[{q:"What runs first: setTimeout(fn, 0) or Promise.then(fn)?",options:["setTimeout","Promise.then","They run at the same time","It is random"],correct:1,explanation:"Promise callbacks are microtasks and have higher priority than setTimeout callbacks (macrotasks). Microtasks always run before macrotasks."},{q:"Is JavaScript multi-threaded?",options:["Yes","No — it is single-threaded with an event loop","Only with Web Workers","Only in Node.js"],correct:1,explanation:"JavaScript is single-threaded. The event loop and Web APIs enable asynchronous behavior without multiple threads."},{q:"What is the call stack?",options:["A list of all variables","Where functions are executed one at a time","A queue of async callbacks","Browser memory"],correct:1,explanation:"The call stack is where function execution contexts are stacked. Functions are pushed when called and popped when they return."}]
  },
  {id:41,unit:3,title:"Version Control & Git Introduction",clo:"CLO11",difficulty:"Beginner",readTime:"8 min",
    theory:"<h3>What Is Version Control?</h3><p>Version control is a system that tracks changes to files over time. It lets you go back to previous versions, collaborate with others, and maintain a complete history of your project.</p><h3>Why Git?</h3><p>Git is the most popular version control system. It is free, open-source, fast, and distributed — every developer has a full copy of the project history on their computer.</p><h3>Key Concepts</h3><ul><li><strong>Repository (repo):</strong> A folder tracked by Git</li><li><strong>Commit:</strong> A snapshot of your files at a point in time</li><li><strong>Working directory:</strong> Your actual files on disk</li><li><strong>Staging area:</strong> Files marked to be included in the next commit</li></ul><div class='analogy-box'><strong>Analogy:</strong> Git is like a save system in a video game. Each commit is a save point. You can go back to any save, create branching storylines, and merge them together.</div>",
    examples:[{title:"Getting started with Git",code:"// These are terminal commands, not JavaScript:\n// git init           → Start tracking a folder\n// git status         → See what files have changed\n// git add index.html → Stage a file\n// git add .          → Stage ALL changed files\n// git commit -m \"Initial commit\" → Save a snapshot\n\nconsole.log('Git is a command-line tool');\nconsole.log('You run Git commands in a terminal');\nconsole.log('Not in the browser!');"}],
    quickRef:[{syntax:"git init",desc:"Initialize a new Git repository"},{syntax:"git status",desc:"Show modified/staged files"},{syntax:"git add <file>",desc:"Stage a file for commit"},{syntax:"git commit -m 'msg'",desc:"Save a snapshot with message"}],
    miniQuiz:[{q:"What is a Git commit?",options:["Deleting files","A snapshot of your project at a point in time","Downloading code","Creating a new file"],correct:1,explanation:"A commit is a recorded snapshot of all staged files at that moment, along with a message describing the changes."},{q:"What does git add do?",options:["Creates a new file","Stages files for the next commit","Commits changes","Pushes to GitHub"],correct:1,explanation:"git add moves files to the staging area — marking them to be included in the next commit."},{q:"What type of version control is Git?",options:["Centralized","Distributed","Cloud-only","Local-only"],correct:1,explanation:"Git is distributed — every developer has a complete copy of the repository and its history on their local machine."}]
  },
  {id:42,unit:3,title:"Git — init, add, commit, status, log",clo:"CLO11",difficulty:"Beginner",readTime:"9 min",
    theory:"<h3>git init</h3><p>Creates a new Git repository in the current folder. Run this once at the start of a project.</p><h3>git add</h3><p>Stages files for the next commit. <code>git add file.js</code> stages one file. <code>git add .</code> stages everything.</p><h3>git commit</h3><p><code>git commit -m \"message\"</code> creates a commit with a descriptive message. Messages should explain what changed and why.</p><h3>git status</h3><p>Shows which files are modified, staged, or untracked. Run this frequently to see your current state.</p><h3>git log</h3><p>Shows commit history — author, date, message, and hash. <code>git log --oneline</code> shows a compact single-line format.</p>",
    examples:[{title:"Basic Git workflow",code:"// Terminal commands for a typical workflow:\n\n// 1. Start a project\n// git init\n\n// 2. Check status\n// git status\n\n// 3. Stage files\n// git add index.html style.css main.js\n// or: git add .\n\n// 4. Commit\n// git commit -m \"Add initial project files\"\n\n// 5. View history\n// git log\n// git log --oneline\n\nconsole.log('The basic workflow: edit → add → commit');"}],
    quickRef:[{syntax:"git init",desc:"Create new repository"},{syntax:"git add .",desc:"Stage all changes"},{syntax:"git commit -m 'msg'",desc:"Commit staged changes"},{syntax:"git log --oneline",desc:"Compact commit history"}],
    miniQuiz:[{q:"What does git status show?",options:["Commit history","Which files are modified, staged, or untracked","Remote repository info","Branch list"],correct:1,explanation:"git status is your go-to command to see the current state — what's changed, what's staged, and what's untracked."},{q:"What does git log --oneline do?",options:["Shows only the last commit","Shows each commit on one line (compact)","Logs errors","Shows file changes"],correct:1,explanation:"git log --oneline shows a compact view with each commit on a single line — just the short hash and message."},{q:"What flag is used to add a commit message?",options:["-m","-msg","--message","-c"],correct:0,explanation:"The -m flag followed by a quoted string provides the commit message: git commit -m 'Your message here'."}]
  },
  {id:43,unit:3,title:"Git Branching — branch, checkout, switch",clo:"CLO11",difficulty:"Intermediate",readTime:"10 min",
    theory:"<h3>What Are Branches?</h3><p>Branches let you work on different features or experiments independently. The default branch is usually called <code>main</code>. Each branch has its own commit history that can diverge from and later merge with other branches.</p><h3>Creating Branches</h3><p><code>git branch feature-name</code> creates a new branch. <code>git checkout -b feature-name</code> creates and switches in one command.</p><h3>Switching Branches</h3><p><code>git checkout branch-name</code> or <code>git switch branch-name</code> switches to a different branch.</p><h3>Why Branch?</h3><ul><li>Work on features without affecting the main code</li><li>Experiment safely — just delete the branch if it fails</li><li>Multiple team members can work in parallel</li></ul>",
    examples:[{title:"Branching commands",code:"// Terminal commands:\n\n// List all branches\n// git branch\n\n// Create a new branch\n// git branch feature-nav\n\n// Switch to that branch\n// git checkout feature-nav\n// or: git switch feature-nav\n\n// Create and switch in one step\n// git checkout -b feature-footer\n\n// Delete a branch (after merging)\n// git branch -d feature-nav\n\nconsole.log('Branches let you work on features independently');"}],
    quickRef:[{syntax:"git branch",desc:"List all branches"},{syntax:"git branch name",desc:"Create new branch"},{syntax:"git checkout -b name",desc:"Create + switch to branch"},{syntax:"git switch name",desc:"Switch to a branch (modern)"}],
    miniQuiz:[{q:"What is the default branch usually called?",options:["master or main","default","root","origin"],correct:0,explanation:"The default branch is traditionally called 'master' but many projects now use 'main' instead."},{q:"How do you create and switch branches in one command?",options:["git branch -s name","git checkout -b name","git create name","git switch --new name"],correct:1,explanation:"git checkout -b name creates a new branch and immediately switches to it."},{q:"Why use branches?",options:["To make the repo larger","To work on features independently without affecting main code","To delete old code","Branches are required by Git"],correct:1,explanation:"Branches let you develop features, fix bugs, or experiment in isolation without affecting the stable main branch."}]
  },
  {id:44,unit:3,title:"Git Merging & Conflict Resolution",clo:"CLO11",difficulty:"Intermediate",readTime:"10 min",
    theory:"<h3>Merging</h3><p><code>git merge branch-name</code> combines the changes from another branch into your current branch. If Git can do it automatically (no conflicts), it creates a merge commit.</p><h3>Merge Conflicts</h3><p>Conflicts occur when two branches modify the same lines of the same file. Git cannot decide which version to keep, so it marks the conflicting sections and asks you to resolve them manually.</p><h3>Resolving Conflicts</h3><ol><li>Open the conflicting file — look for <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt;</code>, <code>=======</code>, and <code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code> markers</li><li>Choose which changes to keep (or combine both)</li><li>Remove the conflict markers</li><li>Stage the resolved file: <code>git add file</code></li><li>Commit: <code>git commit -m 'Resolve merge conflict'</code></li></ol>",
    examples:[{title:"Merging and conflicts",code:"// Merge a branch into main:\n// git checkout main\n// git merge feature-nav\n\n// If there's a conflict, the file looks like:\n// <<<<<<< HEAD\n// console.log('Hello from main');\n// =======\n// console.log('Hello from feature-nav');\n// >>>>>>> feature-nav\n\n// You edit the file to resolve, then:\n// git add resolved-file.js\n// git commit -m 'Resolve merge conflict'\n\nconsole.log('Merge conflicts happen when same lines are edited on different branches');"}],
    quickRef:[{syntax:"git merge branch",desc:"Merge branch into current branch"},{syntax:"<<<<<<< / ======= / >>>>>>>",desc:"Conflict markers in files"},{syntax:"Resolve → git add → git commit",desc:"Steps to fix merge conflicts"}],
    miniQuiz:[{q:"When do merge conflicts occur?",options:["Every time you merge","When two branches modify the same lines","When you create a branch","When you delete a branch"],correct:1,explanation:"Conflicts happen when two branches change the same lines of the same file — Git can't auto-decide which to keep."},{q:"What is the first step to resolve a conflict?",options:["Delete the branch","Open the file and fix the conflicting sections","Run git merge again","Use git reset"],correct:1,explanation:"Open the file, find the conflict markers (<<<<<<, =======, >>>>>>>), decide what to keep, and remove the markers."},{q:"What do you do after resolving a conflict?",options:["Push immediately","git add the file, then git commit","git merge again","Nothing — it auto-resolves"],correct:1,explanation:"After editing the file to resolve conflicts, you must git add the file and then git commit to finalize the merge."}]
  },
  {id:45,unit:3,title:"GitHub — Remote, Push, Pull, Clone",clo:"CLO11",difficulty:"Intermediate",readTime:"10 min",
    theory:"<h3>What Is GitHub?</h3><p>GitHub is a cloud platform for hosting Git repositories. It enables collaboration, code review, issue tracking, and is where most open-source projects live.</p><h3>Remote Repositories</h3><p>A remote is a version of your repo hosted on a server (like GitHub). <code>origin</code> is the conventional name for the main remote.</p><h3>Key Commands</h3><ul><li><code>git remote add origin URL</code> — connect local repo to GitHub</li><li><code>git push -u origin main</code> — upload commits to GitHub</li><li><code>git pull origin main</code> — download and merge remote changes</li><li><code>git clone URL</code> — download an entire repo from GitHub</li><li><code>git fetch</code> — download remote data without merging</li></ul><h3>Collaborative Workflow</h3><p>Fork → Clone → Branch → Commit → Push → Pull Request. This is the standard open-source contribution workflow.</p>",
    examples:[{title:"GitHub workflow",code:"// Connect to GitHub:\n// git remote add origin https://github.com/user/repo.git\n\n// Push your code:\n// git push -u origin main\n\n// Pull latest changes:\n// git pull origin main\n\n// Clone someone's repo:\n// git clone https://github.com/user/repo.git\n\n// Collaboration workflow:\n// 1. Fork the repo on GitHub\n// 2. git clone your-fork-url\n// 3. git checkout -b my-feature\n// 4. Make changes, commit\n// 5. git push origin my-feature\n// 6. Create Pull Request on GitHub\n\nconsole.log('GitHub enables collaboration and sharing');"}],
    quickRef:[{syntax:"git remote add origin URL",desc:"Link local repo to GitHub"},{syntax:"git push origin main",desc:"Upload commits to remote"},{syntax:"git pull origin main",desc:"Download and merge remote changes"},{syntax:"git clone URL",desc:"Download an entire repository"}],
    miniQuiz:[{q:"What is a remote in Git?",options:["A backup file","A version of the repo hosted on a server","A local branch","A Git command"],correct:1,explanation:"A remote is a copy of the repository hosted on a server like GitHub, enabling collaboration and backup."},{q:"What does git clone do?",options:["Creates a branch","Downloads an entire repository from a URL","Copies a single file","Merges two repos"],correct:1,explanation:"git clone downloads a complete copy of a remote repository, including all history and branches."},{q:"What is a Pull Request?",options:["A git pull command","A GitHub feature to propose merging your changes into another branch","A way to download code","A conflict resolution tool"],correct:1,explanation:"A Pull Request (PR) is a GitHub feature where you ask the repo owner to review and merge your branch's changes."}]
  }
);
